global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets:
        - node-monitoring-stack.onrender.com
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true               
