global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'node-app'
    # Render internal networking: service-name.onrender.com
    static_configs:
      - targets: ['https://node-monitoring-stack.onrender.com/']  
    metrics_path: /metrics
    scheme: https                                 # Render uses HTTPS externally
    tls_config:
      insecure_skip_verify: true                  # Render's cert is not in public CA
